---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# datahut

<!-- badges: start -->
<!-- badges: end -->

`datahut` provides datasets for statistical data analysis.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("pridiltal/datahut")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(datahut)
## basic example code
library(fable)
library(ggplot2)
head(touristsl)
autoplot(touristsl)+
  ggtitle("Tourist arrivals to Sri Lanka from 1970 to 2018")+
  xlab("Year") +
  ylab("Tourist Arrivals")
```

```{r}
head(touristsl_monthly)
touristsl_monthly[433:588,]  %>% autoplot()

touristsl_monthly%>% autoplot(Arrivals)
```


```{r}
library(feasts)
touristsl_monthly %>% gg_season(Arrivals, labels = "both") + ylab("Arrivals") +
ggtitle("Seasonal plot: Monthly tourist arrivals to Sri Lanka")
```

```{r}
touristsl_monthly %>%
gg_subseries(Arrivals) + ylab("Arrivals") + ggtitle("Subseries plot: Monthly tourist arrivals to Sri Lanka")

```
